create table if not exists public.servers (
  id text primary key,
  name text not null,
  version text not null default '1.0.0',
  owner_username text not null default 'guest',
  source_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  server_id text not null references public.servers(id) on delete cascade,
  name text not null,
  description text not null,
  input_schema jsonb not null default '{}'::jsonb,
  sql_query text not null,
  operation text not null check (operation in ('SELECT','INSERT','UPDATE','DELETE')),
  created_at timestamptz not null default now(),
  unique (server_id, name)
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  server_id text not null references public.servers(id) on delete cascade,
  name text not null,
  description text not null,
  uri_template text not null,
  sql_query text not null,
  created_at timestamptz not null default now(),
  unique (server_id, name)
);

create table if not exists public.refresh_tokens (
  token_hash text primary key,
  username text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.users (
  username text primary key,
  workspace_id text not null,
  password_hash text not null,
  role text not null check (role in ('admin','user')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.server_auth_config (
  server_id text primary key references public.servers(id) on delete cascade,
  require_mcp_token boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.mcp_tokens (
  id text primary key,
  token_name text not null default '',
  workspace_id text not null,
  subject_username text not null,
  created_by text not null,
  token_hash text not null unique,
  token_value text not null,
  allow_all_servers boolean not null default true,
  allow_all_tools boolean not null default true,
  allow_all_resources boolean not null default true,
  server_ids_json jsonb not null default '[]'::jsonb,
  allowed_tools_json jsonb not null default '[]'::jsonb,
  allowed_resources_json jsonb not null default '[]'::jsonb,
  server_rules_json jsonb not null default '{}'::jsonb,
  tool_rules_json jsonb not null default '{}'::jsonb,
  resource_rules_json jsonb not null default '{}'::jsonb,
  never_expires boolean not null default false,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.mcp_token_policies (
  scope_type text not null check (scope_type in ('global','user','server','tool')),
  scope_id text not null,
  require_mcp_token boolean not null,
  updated_at timestamptz not null default now(),
  primary key (scope_type, scope_id)
);

create index if not exists idx_servers_owner on public.servers(owner_username);
create index if not exists idx_refresh_tokens_user on public.refresh_tokens(username);
create index if not exists idx_users_workspace on public.users(workspace_id);
create index if not exists idx_server_auth_required on public.server_auth_config(require_mcp_token);
create index if not exists idx_mcp_tokens_workspace on public.mcp_tokens(workspace_id);
create index if not exists idx_mcp_tokens_hash on public.mcp_tokens(token_hash);
create index if not exists idx_mcp_token_policies_scope on public.mcp_token_policies(scope_type);
